name: Auto Deploy C# API to VPS

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and publish the project
        run: |
          dotnet clean
          dotnet publish -c Release -o ./publish
          ls -l ./publish

      - name: SSH to VPS and deploy
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_SSH_PASSWORD }}
          port: 24700
          script: |
            cd /home/be2

            # Kiểm tra thư mục publish trên VPS
            ls -l /home/be2/publish

            # Xóa tất cả file trong thư mục publish mà không xóa folder
            find /home/be2/publish/* -type f -exec rm {} \;

            # Kiểm tra lại thư mục publish sau khi xóa file
            ls -l /home/be2/publish

            # Kiểm tra xem thư mục build có chứa file không
            if [ "$(ls -A ./publish)" ]; then
              # Duyệt qua các thư mục trong ./publish và sao chép
              for item in ./publish/*; do
                # Kiểm tra xem item là thư mục, nếu có thì không sao chép
                if [ ! -d "/home/be2/publish/$(basename $item)" ]; then
                  cp -r $item /home/be2/publish/
                fi
              done
            else
              echo "Không có file để sao chép từ máy local."
            fi

            # Kiểm tra xem các file đã được sao chép vào thư mục publish chưa
            ls -l /home/be2/publish

            # Di chuyển lên thư mục gốc của project (nơi có docker-compose.yml)
            cd /home/be2

            # Kiểm tra xem docker-compose.yml có tồn tại trong thư mục hiện tại không
            if [ -f "docker-compose.yml" ]; then
              # Dừng các container Docker hiện tại
              docker-compose down

              # Build lại các container và chạy chúng trong chế độ detached
              docker-compose up -d --build
            else
              echo "Không tìm thấy file docker-compose.yml."
            fi
