name: Auto Deploy C# API to VPS

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and publish the project
        run: |
          dotnet clean
          dotnet publish -c Release -o ./publish
          ls -l ./publish

      - name: SSH to VPS and deploy
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_SSH_PASSWORD }}
          port: 24700
          script: |
            cd /home/be2

            # Tạo thư mục mới nếu chưa có (đã có nên ko tạo)
            # mkdir -p /home/be2/publish_test_auto_deploy

            # Kiểm tra thư mục mới tạo trên VPS
            ls -l /home/be2/publish_test_auto_deploy

            # Xóa tất cả file trong thư mục publish mà không xóa folder
            find /home/be2/publish/* -type f -exec rm {} \;

            # Kiểm tra lại thư mục publish sau khi xóa file
            ls -l /home/be2/publish_test_auto_deploy

            # Kiểm tra xem thư mục build có chứa file không
            if [ "$(ls -A ./publish)" ]; then
              # Copy tất cả file publish từ máy local vào thư mục publish trên VPS
              cp -r ./publish/* /home/be2/publish_test_auto_deploy/
            else
              echo "Không có file để sao chép từ máy local."
            fi

            # Kiểm tra xem các file đã được sao chép vào thư mục publish chưa
            ls -l /home/be2/publish_test_auto_deploy

            # Di chuyển lên thư mục gốc của project
            cd ..

            # Dừng các container Docker hiện tại
            docker-compose down

            # Build lại các container và chạy chúng trong chế độ detached
            docker-compose up -d --build
