name: Auto Deploy C# API to VPS

on:
  push:
    branches:
      - production  

jobs:
  deploy:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'  

      - name: Build và Publish dự án
        run: |
          dotnet clean  
          dotnet publish -c Release -o ./publish 
          ls -l ./publish  

      - name: Copy build lên VPS
        run: |
          scp -P 24700 -r ./publish/* ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/home/be2/publish1/
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock  

      - name: SSH vào VPS và Deploy
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_SSH_PASSWORD }}
          port: 24700
          script: |
            cd /home/be2  

            # Kiểm tra xem file đã được copy lên chưa
            ls -l /home/be2/publish1  

            # Dừng container Docker hiện tại
            # docker-compose down  

            # Build lại container và chạy nó ở chế độ nền
            # docker-compose up -d --build  
